# #####################################################################
# Automatically generated by qmake (2.01a) mer apr 22 11:13:57 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += insertActivity.hpp \
    ../pomotuxdatabase.hpp
SOURCES += insertActivity.cpp \
    main.cpp \
    ../pomotuxdatabase.cpp \
    ../activity.cpp \
    ../activityinventorysheet.cpp \
    ../todotodaysheet.cpp
