
#ifndef _ITODOTODAYSHEET_HPP_
#define _ITODOTODAYSHEET_HPP_
#include "litesql.hpp"
#include "pomotuxdatabase.hpp"
#include <iostream>
#include <string>

//using namespace std;
using namespace litesql;
using namespace pomotuxdatabase;

/**  Interface Class to Todo Today Sheet
 *
 * #include "litesql.hpp"
 * #include "pomotuxdatabase.hpp"
 * -llitesql 
 *
 * Interface class to the one automatically generated by LiteSQL. 
 *  
 * @see pomotuxdatabase.hpp
 */
class ITodoTodaySheet : public TodoTodaySheet {
public:

    /** Default constructor.
     * 	@param a reference to the database object
     */
    ITodoTodaySheet(const litesql::Database& db);

    /** Sets the activity order of an activity already picked up in the todo today sheet
     * 	@param an Integer representing the Order of the activity in the TDTS
     */
    void set_mActivityOrder(int activityOrder);

    /** Returns the activity order of an activity already picked up in the todo today sheet
     * 	@return activity order as integer
     */
    int get_mActivityOrder();

    /** Destructor
     *
     */
    ~ITodoTodaySheet();
};
#endif
